#!/bin/sh
#
# autopkgtest check: Run a limited part of the system-image test suite, from
# its system installed location.  Unlike the smoketest test, this does not
# require network access, so it is compatible with less isolated (but also
# lighter weight) containers such as schroot.
#
# Copyright (C) 2014-2015 Canonical Ltd.
# Author: Barry Warsaw <barry@ubuntu.com>

python3 -m nose2 -vv -P TestCLIMainDryRun
