#!/bin/sh
#
# autopkgtest check: Run a smoke test with actual built system components.
# This requires network access to system-image.ubports.com and is
# isolation-container restricted, so it requires an isolated test container
# like QEMU.
#
# This is like smoketest except that it does a full download.
#
# Copyright (C) 2013-2015 Canonical Ltd.
# Author: Barry Warsaw <barry@ubuntu.com>

set -e
python3 debian/tests/prep.py
system-image-cli -C $ADTTMP/config.d -d mako -c devel -b 0 --no-reboot -v
